import { GiftRarity } from '@dfz/types';

export interface GiftCatalogItem {
  name: string;
  slug: string;
  description: string;
  artwork: string;
  priceStars: number;
  rarity: GiftRarity;
  category: 'popular' | 'limited' | 'collectible' | 'premium' | 'legendary';
  isLimited: boolean;
  totalSupply?: number;
  isPremiumOnly?: boolean;
  isCollectibleEligible?: boolean;
}

export const ALL_100_GIFTS: GiftCatalogItem[] = [
  // ==========================================
  // 1-35: POPULAR & REGULAR GIFTS (35 items)
  // ==========================================
  {
    name: 'Neon Rose',
    slug: 'neon-rose',
    description: 'Светящаяся неоновая роза с голографическими лепестками',
    artwork: 'rose',
    priceStars: 50,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Cyber Heart',
    slug: 'cyber-heart',
    description: 'Пульсирующее неоновое сердце симпатии и доверия',
    artwork: 'heart',
    priceStars: 75,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Birthday Cake',
    slug: 'birthday-cake',
    description: 'Праздничный торт с горящими неоновыми свечами',
    artwork: 'cake',
    priceStars: 100,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Sparkling Wine',
    slug: 'sparkling-wine',
    description: 'Бутылка элитного игристого для ярких торжеств',
    artwork: 'wine',
    priceStars: 120,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Morning Coffee',
    slug: 'morning-coffee',
    description: 'Горячий ароматный кофе для бодрого начала дня',
    artwork: 'coffee',
    priceStars: 35,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Lucky Clover',
    slug: 'lucky-clover',
    description: 'Четырехлистный изумрудный клевер удачи',
    artwork: 'clover',
    priceStars: 60,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Sweet Candy',
    slug: 'sweet-candy',
    description: 'Сладкий неоновый леденец для хорошего настроения',
    artwork: 'candy',
    priceStars: 30,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Party Popper',
    slug: 'party-popper',
    description: 'Хлопушка с золотым и сияющим конфетти',
    artwork: 'party',
    priceStars: 65,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Cyber Teddy',
    slug: 'cyber-teddy',
    description: 'Плюшевый мишка с цифровым сердцем',
    artwork: 'teddy',
    priceStars: 95,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Golden Star',
    slug: 'golden-star',
    description: 'Золотая сияющая звезда уважения и дружбы',
    artwork: 'star',
    priceStars: 100,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Blue Diamond',
    slug: 'blue-diamond',
    description: 'Сверкающий сапфировый бриллиант чистой огранки',
    artwork: 'diamond',
    priceStars: 150,
    rarity: GiftRarity.RARE,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Pizza Slice',
    slug: 'pizza-slice',
    description: 'Горячий ломтик пиццы для душевного диалога',
    artwork: 'pizza',
    priceStars: 40,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Magic Cookie',
    slug: 'magic-cookie',
    description: 'Печенье с вдохновляющим предсказанием внутри',
    artwork: 'cookie',
    priceStars: 30,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Lucky Horseshoe',
    slug: 'lucky-horseshoe',
    description: 'Золотая подкова на неисчерпаемую удачу',
    artwork: 'horseshoe',
    priceStars: 85,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Midnight Owl',
    slug: 'midnight-owl',
    description: 'Мудрая полуночная сова с горящими глазами',
    artwork: 'owl',
    priceStars: 140,
    rarity: GiftRarity.RARE,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Neon Lily',
    slug: 'neon-lily',
    description: 'Нежная неоновая водяная лилия чистоты',
    artwork: 'lily',
    priceStars: 70,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Cherry Sakura',
    slug: 'cherry-sakura',
    description: 'Ветка цветущей весенней сакуры',
    artwork: 'sakura',
    priceStars: 90,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Retro Cassette',
    slug: 'retro-cassette',
    description: 'Винтажная аудиокассета с любимыми треками',
    artwork: 'cassette',
    priceStars: 80,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Game Controller',
    slug: 'game-controller',
    description: 'Геймпад настоящего про-геймера',
    artwork: 'gamepad',
    priceStars: 120,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Space Donut',
    slug: 'space-donut',
    description: 'Глазированный пончик с космической посыпкой',
    artwork: 'donut',
    priceStars: 50,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Peace Dove',
    slug: 'peace-dove',
    description: 'Белый голубь гармонии и добрых вестей',
    artwork: 'dove',
    priceStars: 110,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Hologram Feather',
    slug: 'hologram-feather',
    description: 'Легкое голографическое перо вдохновения',
    artwork: 'feather',
    priceStars: 85,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Melody Note',
    slug: 'melody-note',
    description: 'Золотая нота для тех, кто слышит ритм жизни',
    artwork: 'note',
    priceStars: 45,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Golden Bell',
    slug: 'golden-bell',
    description: 'Звонкий колокольчик приятных уведомлений',
    artwork: 'bell',
    priceStars: 75,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Scarlet Balloon',
    slug: 'scarlet-balloon',
    description: 'Алый праздничный шарик улетающий к мечтам',
    artwork: 'balloon',
    priceStars: 25,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Rainbow Prism',
    slug: 'rainbow-prism',
    description: 'Оптическая призма, преломляющая свет в спектр',
    artwork: 'prism',
    priceStars: 130,
    rarity: GiftRarity.RARE,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Magic Mushroom',
    slug: 'magic-mushroom',
    description: 'Биолюминесцентный гриб из сказочного киберлеса',
    artwork: 'mushroom',
    priceStars: 65,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Origami Crane',
    slug: 'origami-crane',
    description: 'Бумажный журавлик исполнения заветных желаний',
    artwork: 'crane',
    priceStars: 95,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Frost Snowflake',
    slug: 'frost-snowflake',
    description: 'Изящная ледяная снежинка вечной свежести',
    artwork: 'snowflake',
    priceStars: 80,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Solar Sun',
    slug: 'solar-sun',
    description: 'Сияющее теплое солнце радости и энергии',
    artwork: 'sun',
    priceStars: 120,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Crescent Moon',
    slug: 'crescent-moon',
    description: 'Таинственный полумесяц тихой ночи',
    artwork: 'moon',
    priceStars: 110,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Cyber Berry',
    slug: 'cyber-berry',
    description: 'Сочная неоновая ягода для приятного момента',
    artwork: 'strawberry',
    priceStars: 55,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Victory Trophy',
    slug: 'victory-trophy',
    description: 'Кубок абсолютного триумфа и превосходства',
    artwork: 'trophy',
    priceStars: 180,
    rarity: GiftRarity.RARE,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Silver Medal',
    slug: 'silver-medal',
    description: 'Серебряная медаль высокого мастерства',
    artwork: 'medal',
    priceStars: 100,
    rarity: GiftRarity.COMMON,
    category: 'popular',
    isLimited: false,
  },
  {
    name: 'Magic Wand',
    slug: 'magic-wand',
    description: 'Волшебная палочка, творящая чудеса',
    artwork: 'wand',
    priceStars: 140,
    rarity: GiftRarity.RARE,
    category: 'popular',
    isLimited: false,
  },

  // ==========================================
  // 36-55: RARE & PREMIUM GIFTS (20 items)
  // ==========================================
  {
    name: 'Quantum Rocket',
    slug: 'quantum-rocket',
    description: 'Сверхсветовая ракета к новым горизонтам',
    artwork: 'rocket',
    priceStars: 500,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Golden Crown',
    slug: 'golden-crown',
    description: 'Корона признания и безупречного статуса',
    artwork: 'crown',
    priceStars: 1000,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
    isPremiumOnly: true,
  },
  {
    name: 'Platinum Ring',
    slug: 'platinum-ring',
    description: 'Кольцо из платины с вечным бриллиантом',
    artwork: 'ring',
    priceStars: 1200,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Imperial Scepter',
    slug: 'imperial-scepter',
    description: 'Императорский скипетр безграничного авторитета',
    artwork: 'scepter',
    priceStars: 1500,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
    isPremiumOnly: true,
  },
  {
    name: 'Cyber Skull',
    slug: 'cyber-skull',
    description: 'Хромированный череп киберпанк-эпохи',
    artwork: 'skull',
    priceStars: 750,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Astral Compass',
    slug: 'astral-compass',
    description: 'Компас, указывающий путь сквозь созвездия',
    artwork: 'compass',
    priceStars: 800,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Neon Butterfly',
    slug: 'neon-butterfly',
    description: 'Бабочка с крыльями из чистого светодиодного пламени',
    artwork: 'butterfly',
    priceStars: 650,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Cybernetic Eye',
    slug: 'cybernetic-eye',
    description: 'Всевидящее кибероко квантового предвидения',
    artwork: 'eye',
    priceStars: 850,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Hologram Lotus',
    slug: 'hologram-lotus',
    description: 'Цветок духовного равновесия и гармонии',
    artwork: 'lotus',
    priceStars: 900,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
    isPremiumOnly: true,
  },
  {
    name: 'Midnight Wolf',
    slug: 'midnight-wolf',
    description: 'Тотем волка лунной ночи и преданности стае',
    artwork: 'wolf',
    priceStars: 1100,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Cyber Panther',
    slug: 'cyber-panther',
    description: 'Быстрая и грациозная неоновая пантера',
    artwork: 'panther',
    priceStars: 1300,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Solar Flare',
    slug: 'solar-flare',
    description: 'Сгусток протуберанца солнечной бури',
    artwork: 'solar',
    priceStars: 950,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Celestial Globe',
    slug: 'celestial-globe',
    description: 'Армадиллярная сфера движения планет',
    artwork: 'globe',
    priceStars: 1250,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
    isPremiumOnly: true,
  },
  {
    name: 'Golden Key',
    slug: 'golden-key',
    description: 'Ключ от всех закрытых дверей и тайн',
    artwork: 'key',
    priceStars: 850,
    rarity: GiftRarity.RARE,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Infinity Loop',
    slug: 'infinity-loop',
    description: 'Символ бесконечности из переливающегося титана',
    artwork: 'infinity',
    priceStars: 1400,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Golden Bull',
    slug: 'golden-bull',
    description: 'Символ непреодолимого роста и финансовой мощи',
    artwork: 'bull',
    priceStars: 1800,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
    isPremiumOnly: true,
  },
  {
    name: 'Cyber Eagle',
    slug: 'cyber-eagle',
    description: 'Орел парящий над вершинами виртуального мира',
    artwork: 'eagle',
    priceStars: 1350,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Emerald Scarab',
    slug: 'emerald-scarab',
    description: 'Изумрудный скарабей вечного перерождения',
    artwork: 'scarab',
    priceStars: 1100,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Ruby Heart',
    slug: 'ruby-heart',
    description: 'Пылающее сердце из цельного бирманского рубина',
    artwork: 'ruby',
    priceStars: 1500,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },
  {
    name: 'Sapphire Drop',
    slug: 'sapphire-drop',
    description: 'Глубокая сапфировая слеза океана',
    artwork: 'sapphire',
    priceStars: 1250,
    rarity: GiftRarity.EPIC,
    category: 'premium',
    isLimited: false,
  },

  // ==========================================
  // 56-75: LIMITED EDITION GIFTS (20 items)
  // ==========================================
  {
    name: 'Quantum Crystal',
    slug: 'quantum-crystal',
    description: 'Чистый кристалл гиперпространственной энергии',
    artwork: 'crystal',
    priceStars: 2500,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 2500,
  },
  {
    name: 'Amethyst Geode',
    slug: 'amethyst-geode',
    description: 'Природная аметистовая друза редкой чистоты',
    artwork: 'amethyst',
    priceStars: 2000,
    rarity: GiftRarity.RARE,
    category: 'limited',
    isLimited: true,
    totalSupply: 2000,
  },
  {
    name: 'Chrono Pocketwatch',
    slug: 'chrono-pocketwatch',
    description: 'Механические карманные часы с турбийоном',
    artwork: 'pocketwatch',
    priceStars: 2800,
    rarity: GiftRarity.EPIC,
    category: 'limited',
    isLimited: true,
    totalSupply: 1500,
  },
  {
    name: 'Cyber Helmet',
    slug: 'cyber-helmet',
    description: 'Тактический шлем пилота квантовых истребителей',
    artwork: 'helmet',
    priceStars: 1900,
    rarity: GiftRarity.RARE,
    category: 'limited',
    isLimited: true,
    totalSupply: 3000,
  },
  {
    name: 'Plasma Sword',
    slug: 'plasma-sword',
    description: 'Клинок из сфокусированной высокотемпературной плазмы',
    artwork: 'sword',
    priceStars: 2400,
    rarity: GiftRarity.EPIC,
    category: 'limited',
    isLimited: true,
    totalSupply: 2000,
  },
  {
    name: 'Aegis Shield',
    slug: 'aegis-shield',
    description: 'Легендарный щит непробиваемой цифровой обороны',
    artwork: 'shield',
    priceStars: 2200,
    rarity: GiftRarity.EPIC,
    category: 'limited',
    isLimited: true,
    totalSupply: 2500,
  },
  {
    name: 'Quantum Hourglass',
    slug: 'quantum-hourglass',
    description: 'Песочные часы с квантовым гравитационным песком',
    artwork: 'hourglass',
    priceStars: 2600,
    rarity: GiftRarity.EPIC,
    category: 'limited',
    isLimited: true,
    totalSupply: 1800,
  },
  {
    name: 'Golden Chalice',
    slug: 'golden-chalice',
    description: 'Кубок победителей из чистого червонного золота',
    artwork: 'chalice',
    priceStars: 3000,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1500,
  },
  {
    name: 'Diamond Anchor',
    slug: 'diamond-anchor',
    description: 'Алмазный якорь стойкости среди бурь',
    artwork: 'anchor',
    priceStars: 1800,
    rarity: GiftRarity.RARE,
    category: 'limited',
    isLimited: true,
    totalSupply: 2200,
  },
  {
    name: 'Cyber Griffin',
    slug: 'cyber-griffin',
    description: 'Крылатый грифон со стальными перьями',
    artwork: 'griffin',
    priceStars: 3200,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1200,
  },
  {
    name: 'Pegasus Wings',
    slug: 'pegasus-wings',
    description: 'Сияющие крылья для полета к звездам',
    artwork: 'wings',
    priceStars: 3500,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1000,
  },
  {
    name: 'Mecha Tiger',
    slug: 'mecha-tiger',
    description: 'Механический тигр с неоновыми полосами',
    artwork: 'tiger',
    priceStars: 3800,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1200,
  },
  {
    name: 'Golden Falcon',
    slug: 'golden-falcon',
    description: 'Охотничий сокол высшей знати',
    artwork: 'falcon',
    priceStars: 3600,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1500,
  },
  {
    name: 'Cyber Kraken',
    slug: 'cyber-kraken',
    description: 'Глубинный левиафан цифровых пучин',
    artwork: 'kraken',
    priceStars: 4000,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1000,
  },
  {
    name: 'Golden Anubis',
    slug: 'golden-anubis',
    description: 'Страж вечности из древнейшего пантеона',
    artwork: 'anubis',
    priceStars: 4200,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1000,
  },
  {
    name: 'Valkyrie Helm',
    slug: 'valkyrie-helm',
    description: 'Шлем северной воительницы Вальхаллы',
    artwork: 'valkyrie',
    priceStars: 3900,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1100,
  },
  {
    name: 'Cyber Cerberus',
    slug: 'cyber-cerberus',
    description: 'Трехглавый страж цифровых врат',
    artwork: 'cerberus',
    priceStars: 4100,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 900,
  },
  {
    name: 'Astral Unicorn',
    slug: 'astral-unicorn',
    description: 'Единорог звездного сияния и благородства',
    artwork: 'unicorn',
    priceStars: 4500,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 850,
  },
  {
    name: 'Quantum Orb',
    slug: 'quantum-orb',
    description: 'Сфера вероятностей будущего времени',
    artwork: 'orb',
    priceStars: 3400,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1400,
  },
  {
    name: 'Nebula Butterfly',
    slug: 'nebula-butterfly',
    description: 'Бабочка сотканная из межзвездной туманности',
    artwork: 'nebula-bf',
    priceStars: 3700,
    rarity: GiftRarity.LEGENDARY,
    category: 'limited',
    isLimited: true,
    totalSupply: 1200,
  },

  // ==========================================
  // 76-90: NFT COLLECTIBLES (15 items)
  // ==========================================
  {
    name: 'Crystal Dragon',
    slug: 'crystal-dragon',
    description: 'Лимитированный страж цифровой вселенной DFZ (NFT-тираж)',
    artwork: 'dragon',
    priceStars: 6000,
    rarity: GiftRarity.LEGENDARY,
    category: 'collectible',
    isLimited: true,
    totalSupply: 1000,
    isCollectibleEligible: true,
  },
  {
    name: 'Genesis Phoenix',
    slug: 'genesis-phoenix',
    description: 'Мифический феникс возрождения из первого тиража DFZ',
    artwork: 'phoenix',
    priceStars: 10000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 500,
    isCollectibleEligible: true,
  },
  {
    name: 'Cyber Leviathan',
    slug: 'cyber-leviathan',
    description: 'NFT-артефакт древнего хозяина сети',
    artwork: 'leviathan',
    priceStars: 8500,
    rarity: GiftRarity.LEGENDARY,
    category: 'collectible',
    isLimited: true,
    totalSupply: 750,
    isCollectibleEligible: true,
  },
  {
    name: 'Chrono Matrix',
    slug: 'chrono-matrix',
    description: 'Коллекционная матрица управления потоками данных',
    artwork: 'matrix',
    priceStars: 7000,
    rarity: GiftRarity.LEGENDARY,
    category: 'collectible',
    isLimited: true,
    totalSupply: 900,
    isCollectibleEligible: true,
  },
  {
    name: 'Singularity Core',
    slug: 'singularity-core',
    description: 'Ядро первичной гравитационной сингулярности',
    artwork: 'singularity',
    priceStars: 12000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 300,
    isCollectibleEligible: true,
  },
  {
    name: 'Cyber Samurai',
    slug: 'cyber-samurai',
    description: 'Доспех самурая кодекса Бусидо цифрового века',
    artwork: 'samurai',
    priceStars: 9000,
    rarity: GiftRarity.LEGENDARY,
    category: 'collectible',
    isLimited: true,
    totalSupply: 600,
    isCollectibleEligible: true,
  },
  {
    name: 'Quantum Hypercube',
    slug: 'quantum-hypercube',
    description: 'Четырехмерный тессеракт гиперпространства',
    artwork: 'hypercube',
    priceStars: 9500,
    rarity: GiftRarity.LEGENDARY,
    category: 'collectible',
    isLimited: true,
    totalSupply: 500,
    isCollectibleEligible: true,
  },
  {
    name: 'Dark Matter Shard',
    slug: 'dark-matter-shard',
    description: 'Фрагмент темной материи глубокого космоса',
    artwork: 'darkmatter',
    priceStars: 15000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 250,
    isCollectibleEligible: true,
  },
  {
    name: 'Celestial Pegasus',
    slug: 'celestial-pegasus',
    description: 'Крылатый конь верховных божеств Олимпа',
    artwork: 'pegasus',
    priceStars: 11000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 400,
    isCollectibleEligible: true,
  },
  {
    name: 'Golden Scarab NFT',
    slug: 'golden-scarab-nft',
    description: 'Инкрустированный бриллиантами золотой скарабей',
    artwork: 'scarab-nft',
    priceStars: 13500,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 300,
    isCollectibleEligible: true,
  },
  {
    name: 'Cyber Titan',
    slug: 'cyber-titan',
    description: 'Титанический страж рубежей DFZ Chain',
    artwork: 'titan',
    priceStars: 16000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 200,
    isCollectibleEligible: true,
  },
  {
    name: 'Diamond Cyber Skull',
    slug: 'diamond-cyber-skull',
    description: 'Череп из черного и прозрачного алмаза с лазерной гравировкой',
    artwork: 'skull-nft',
    priceStars: 17500,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 150,
    isCollectibleEligible: true,
  },
  {
    name: 'Solar Lion NFT',
    slug: 'solar-lion-nft',
    description: 'Царственный лев с огненной короной солнца',
    artwork: 'lion',
    priceStars: 14000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 350,
    isCollectibleEligible: true,
  },
  {
    name: 'Quantum Vortex',
    slug: 'quantum-vortex',
    description: 'Вращающийся вихрь неизведанных измерений',
    artwork: 'vortex',
    priceStars: 12500,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 450,
    isCollectibleEligible: true,
  },
  {
    name: 'Cyber Archangel',
    slug: 'cyber-archangel',
    description: 'Архангел света и справедливости с пламенным мечом',
    artwork: 'archangel',
    priceStars: 18000,
    rarity: GiftRarity.MYTHIC,
    category: 'collectible',
    isLimited: true,
    totalSupply: 150,
    isCollectibleEligible: true,
  },

  // ==========================================
  // 91-100: MYTHIC & LEGENDARY MASTERPIECES (10 items)
  // ==========================================
  {
    name: 'Sovereign Crown of DFZ',
    slug: 'sovereign-crown',
    description: 'Верховная корона суверенитета платформы DFZ',
    artwork: 'sovereign',
    priceStars: 25000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 100,
    isCollectibleEligible: true,
  },
  {
    name: 'Heart of the Galaxy',
    slug: 'heart-of-galaxy',
    description: 'Пульсирующее сердце галактического ядра',
    artwork: 'galaxy-heart',
    priceStars: 30000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 75,
    isCollectibleEligible: true,
  },
  {
    name: 'Eternal Infinity Gauntlet',
    slug: 'infinity-gauntlet',
    description: 'Перчатка бесконечности управляющая тканью реальности',
    artwork: 'gauntlet',
    priceStars: 35000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 50,
    isCollectibleEligible: true,
  },
  {
    name: 'Quantum Black Hole',
    slug: 'quantum-black-hole',
    description: 'Компактная черная дыра в стазисном квантовом поле',
    artwork: 'blackhole',
    priceStars: 40000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 40,
    isCollectibleEligible: true,
  },
  {
    name: 'Primordial Dragon Egg',
    slug: 'primordial-dragon-egg',
    description: 'Драконье яйцо первозданного огня и магии',
    artwork: 'dragon-egg',
    priceStars: 28000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 80,
    isCollectibleEligible: true,
  },
  {
    name: 'Golden Throne of DFZ',
    slug: 'golden-throne',
    description: 'Трон абсолютного величия и непревзойденного статуса',
    artwork: 'throne',
    priceStars: 50000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 25,
    isCollectibleEligible: true,
  },
  {
    name: 'Celestial Stargate',
    slug: 'celestial-stargate',
    description: 'Врата межгалактических переходов древней цивилизации',
    artwork: 'stargate',
    priceStars: 45000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 30,
    isCollectibleEligible: true,
  },
  {
    name: 'Staff of the Cosmos',
    slug: 'cosmos-staff',
    description: 'Посох повелителя времени и пространственных струн',
    artwork: 'cosmos-staff',
    priceStars: 32000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 60,
    isCollectibleEligible: true,
  },
  {
    name: 'Eye of the Universe',
    slug: 'universe-eye',
    description: 'Око смотрящее сквозь все измерения бытия',
    artwork: 'universe-eye',
    priceStars: 48000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 25,
    isCollectibleEligible: true,
  },
  {
    name: 'Omega DFZ Singularity',
    slug: 'omega-singularity',
    description: 'Высший артефакт вселенной DFZ. Абсолютный тираж 10 экземпляров.',
    artwork: 'omega',
    priceStars: 100000,
    rarity: GiftRarity.MYTHIC,
    category: 'legendary',
    isLimited: true,
    totalSupply: 10,
    isCollectibleEligible: true,
  },
];
