version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dfz-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dfz_messenger
    ports:
      - "5432:5432"
    volumes:
      - dfz_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dfz-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - dfz_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: dfz-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - dfz_miniodata:/data

  api:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.api
    container_name: dfz-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/dfz_messenger?schema=public
      REDIS_URL: redis://redis:6379
      JWT_ACCESS_SECRET: dfz_production_access_secret_2026
      JWT_REFRESH_SECRET: dfz_production_refresh_secret_2026
      CLIENT_URL: http://localhost:3000
      STORAGE_DRIVER: local
      UPLOAD_DIR: /app/uploads
    ports:
      - "4000:4000"
    volumes:
      - dfz_uploads:/app/uploads

  web:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.web
    container_name: dfz-web
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_WS_URL: http://localhost:4000
    ports:
      - "3000:3000"

volumes:
  dfz_pgdata:
  dfz_redisdata:
  dfz_miniodata:
  dfz_uploads:
